##############################################
spring:
  profiles:
    include: secret

  datasource:
    username: lim
    url: jdbc:postgresql://localhost:5432/weather #jdbc:h2:mem:city
    password: milmil
    driverClassName: org.postgresql.Driver #org.h2.Driver

  h2:
    console:
      enabled: 'true'
      path: /h2-console

  application:
    name: Weather

  main:
    banner-mode: off

  servlet:
    context-path: /

  flyway:
    clean-disabled: false # Разрешить очистку
    locations: classpath:sql
    baseline-on-migrate: true
    enabled: true

##############################################
management:
  endpoints:
    web:
      exposure:
        include: mappings

##############################################